Java spring boot update day 1
thinkb4/a-walk-in-graphql pull request #86
Opened 2023-08-14 13:45 UTC by sciappesoni

2023-08-14 14:32 UTC, Jaxolotl requested changes
some small typos and documentation text fixes

2023-08-14 14:32 UTC, Jaxolotl commented on setup/java.md
> +* `java` Java JVM to be used for compile an run the code. (Required to use java source code)
TYPO: compile ~an~ and run the code

2023-08-14 14:32 UTC, Jaxolotl commented on setup/java.md
> +* `org.springframework.boot` Spring boot frework ot be used into the project. (Required to use spring boot)
> Spring boot **frework ot** be used
🤨  what?

2023-08-14 14:32 UTC, Jaxolotl commented on setup/java.md
> +  The field resolver is any method contatined into the "Entity Resolver" in the Spring Context that has the same name as the data bean, with the suffix @SchemaMapping spring annotation. Methods on th
> Methods on the field resolver bean follow all of the same rules as on the data bean but are also provided the data bean itself as a first parameter.

Not sure if I understand the last part (but are also provided the ...)

2023-08-14 14:32 UTC, Jaxolotl commented on setup/java.md
> +The Gradle Wrapper is an excellent choice for projects that need a specific version depdency from Maven central or custom respositories.
> from Maven central or

is that correct?

2023-08-15 13:05 UTC, Jaxolotl approved these changes, later dismissed

2023-08-15 13:09 UTC, gribaudof-LNRS commented on .gitignore
>  !.mvn/wrapper/maven-wrapper.jar
Se podría eliminar esta exclusion ya que se reempazo por el wrapper de gradle
```suggestion

```

2023-08-15 13:18 UTC, Jaxolotl approved these changes, later dismissed

2023-08-15 13:28 UTC, gribaudof-LNRS commented on lessons/day_01/java/src/main/java/com/example/DemoGraphQL/model/Skill.java
> +                ", parent=" + (parent != null ? parent.name : "null") +
esto no seria necesario ya que el operador + hace lo mismo

2023-08-15 13:34 UTC, gribaudof-LNRS commented on lessons/day_01/java/gradle.properties
> +kotlin.version=1.3.70
Para que se necesita setear esta propiedad?

2023-08-15 13:36 UTC, gribaudof-LNRS commented on setup/java.md
>  * [Linux RPM and DEB installer packages](https://adoptopenjdk.net/installation.html?variant=openjdk8&jvmVariant=hotspot#linux-pkg)
Necesitas actualizar estos links a la version 17

2023-08-15 13:42 UTC, gribaudof-LNRS commented on setup/java.md
> +3. run `./gradle run `(linux) or `gradle.bat run`(windows) to start the GraphQL server.
El plugin de gradle para springboot proporciona la tarea "bootRun" que permite ejecutar la aplicación sin necesidad de compilarla primero.

2023-08-15 13:45 UTC, gribaudof-LNRS commented on setup/java.md
> +To display a GUI for editing and testing GraphQL queries and mutations against the server you can open your browser and type [http://localhost:8080/graphiql](http://localhost:8080/graphiql)
recuerda que yo había agregado playground ya que era la tool utilizada en la teroría y por el resto de los lenguajes, si la teroría va a seguir mostrando los ejemplos en playground sugiero mantenerlo.

2023-08-15 18:18 UTC, fgriba approved these changes

2023-08-15 19:10 UTC, Jaxolotl approved these changes

2023-08-15 19:15 UTC, merged