Java spring boot update remaining days
thinkb4/a-walk-in-graphql pull request #89
Opened 2023-08-18 21:32 UTC by sciappesoni

2023-08-22 12:34 UTC, Jaxolotl requested changes

2023-08-22 12:34 UTC, Jaxolotl commented on lessons/day_03/java/README.md
> +## Day 2 exercise - Java
This is pointing to day 2 but it's day 😉

2023-08-22 12:34 UTC, Jaxolotl commented on lessons/day_03/java/src/main/java/com/example/DemoGraphQL/service/PersonService.java
inputs are nor necessary anymore here?

2023-08-22 12:34 UTC, Jaxolotl commented on lessons/day_04/java/README.md
> +## Day 2 exercise - Java
oops should be day 4

2023-08-22 12:34 UTC, Jaxolotl commented on lessons/day_05/java/README.md
> +## Day 2 exercise - Java
day 5 😜

2023-08-22 12:34 UTC, Jaxolotl commented on lessons/day_06/java/README.md
> +## Day 2 exercise - Java
day 6 😮

2023-08-22 12:34 UTC, Jaxolotl commented on lessons/day_07/java/README.md
> +## Day 2 exercise - Java
day 7

2023-08-22 12:34 UTC, Jaxolotl commented on lessons/day_07/java/README.md
> -* `graphql-java` provides the `GraphQLError` interface representing a GraphQL standard error that our exceptions will implement.
remember to restore the hints

2023-08-22 12:34 UTC, Jaxolotl commented on lessons/day_03/java/README.md
> -Read the instructions on the [Day 3 exercise](../day_03.md#exercise) definition
restore the hints

2023-08-22 12:34 UTC, Jaxolotl commented on lessons/day_04/java/README.md
> -Read the instructions on the [Day 4 exercise](../day_04.md#exercise) definition
restore the hints

2023-08-22 12:34 UTC, Jaxolotl commented on lessons/day_05/java/README.md
> -Read the instructions on the [Day 5 exercise](../day_05.md#exercise) definition
restore the hints

2023-08-22 12:34 UTC, Jaxolotl commented on lessons/day_06/java/README.md
> -Read the instructions on the [Day 6 exercise](../day_06.md#exercise) definition
restore the hints

2023-08-22 15:15 UTC, fgriba commented on lessons/day_05/java/src/main/resources/Java_day_05_Interfaces_and_Unions_hint.patch
> -Index: lessons/day_05/java/src/main/java/com/example/DemoGraphQL/resolver/PersonResolver.java
Sólo por curiosidad 😃 , en la primera edición del curso las resoluciones del día anterior las dábamos en estos patchs para que los participantes del curso puedan aplicarlos. Se decidió no hacer más esto y ahora la resolución va derecho en el código?

2023-08-22 15:23 UTC, fgriba commented on lessons/day_02/java/src/main/java/com/example/DemoGraphQL/resolver/SkillResolver.java
> +    @SchemaMapping(field = "parent")
**FRIENDLY SUGGESTION**
Leyendo [la doc de este nuevo soporte por parte de Spring](https://docs.spring.io/spring-graphql/docs/current/reference/html/#controllers-declaration):
> The @SchemaMapping annotation can also omit those attributes, in which case the field name defaults to the method name, while the type name defaults to the simple class name of the source object/ main injected into the method.

Creo que sería útil para explicar tener uno de estos resolvers con los valores por defecto.

2023-08-23 13:07 UTC, fgriba commented on lessons/day_06/java/src/main/java/com/example/DemoGraphQL/resolver/ContactResolver.java
> -public class ContactResolver extends PersonResolver<Contact> {
Probar si anotando la clase nos permite utilizar todo lo definido en la superclase:
```
@Controller
@SchemaMapping(typeName="Contact")
public class ContactResolver extends PersonResolver<Contact> {
```

2023-08-23 13:15 UTC, fgriba commented on lessons/day_04/java/src/main/java/com/example/DemoGraphQL/resolver/SkillResolver.java
> +    public Optional<Skill> skill(@Argument final InputSkill input) {
**FRIENDLY SUGGESTION - No obligatorio ya que esta relacionado con Java y no con GraphQl**
Ya que estamos utilizando Java17, estaría bueno ver si podemos reemplazar estas clases **InputSkill.java** y **InputPerson.java** por [Records](https://www.baeldung.com/java-record-keyword)

>Passing immutable data between objects is one of the most common, but mundane tasks in many Java applications.
Prior to Java 14, this required the creation of a class with boilerplate fields and methods, which were susceptible to trivial mistakes and muddled intentions.
With the release of Java 14, we can now use records to remedy these problems.

2023-08-23 13:30 UTC, fgriba commented on lessons/day_03/java/src/main/java/com/example/DemoGraphQL/service/PersonService.java
>  public class PersonService {
A partir de la linea 66 se encuentra el código comentado para el hint de este día. En esta implementacion se crea un Example para ser utilizado en QueryByExample. **Sugiero que revises el nuevo soporte para esta funcionalidad**: https://docs.spring.io/spring-graphql/docs/current/reference/html/#data.querybyexample

2023-08-26 18:53 UTC, fgriba commented on lessons/day_04/java/src/main/java/com/example/DemoGraphQL/service/SkillService.java
>  import org.springframework.data.domain.Example;
Ambos servicios siguen utilizando la implementacion de *queryByExample* que utilicé yo en la primera edición de curso. Afortunadamente el nuevo soporte de Springboot siguió con el mismo enfoque pero se han agregado algunas clases y configuraciones nuevas que sugiero utilicemos en lo posible, ej: *QueryByExampleDataFetcher*
Para más detalle ir a la doc: https://docs.spring.io/spring-graphql/docs/current/reference/html/#data.querybyexample

2023-08-29 13:00 UTC, fgriba approved these changes
Decidimos seguir con estos cambios y luego se creará un nuevo pr si hay tiempo con ejemplos de uso de QueryByExampleDataFetcher.

2023-08-29 15:46 UTC, Jaxolotl approved these changes

2023-08-29 16:17 UTC, merged